name: Update
on:
  workflow_dispatch:
  schedule:
    # Once a day at 7AM
    - cron: 0 15 * * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2.0.0
        with:
          feed-url: https://chadbaldwin.net/feed.xml
          readme-section: posts
          branch: main
